sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- 'pypy'
install:
- pip install tox
- TOX_ENV=${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}}
script: tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - $HOME/.cache/pip
deploy:
  provider: pypi
  user: mattcl
  on:
    tags: true
    branch: master
  password:
    secure: iCiZaXPREAv0w+wKh3Wp8d07uRlyGOOTcnNoihw5ohqRIsu6oaoALnkgeLQf6sO7ZQcy5sjdJgitGEjNF5TGQl3s1cmntk8C53H++2bCVgPpLrQMpQUWOzdLDnoeW2q/qLxSJ0qQTsWPPgvJVAfVS8AtWchVRD4urDFKHg7lVOf10tp09YKnyhar6hUjrFQt6F9qMLcVxlVyWUBCspPfyCBLCCMCnLGP15PH//Sz9TrVAbM0C2S6M4g2wcbwcbaM3D1eegTe+J5e5dPHl2Tl7MtaNfAQRaHfAKpzCfJ3v3wvD228Hs/YmuB5SmwEdcclm9YIUhEJgsOBTwVctHwy5EhLGaevxVZs6oGvJzJLTYmQtBmFg3uHpnZDTkh5vcSYoTa7WGSMzRwTvqEJLliItC37VT+jOHma59TgW4a9xXYJMJ1G+tkLXFPJzzeFEKYPmguPzKLoI+DB0KH8t9I9ZucR+Uq0q7OPL6q0MUSX4yWR7z//nV6Hz8bJWRGCEhpht911Kk3mrcNGw9bX91eMqIdJxbAIo2l/4ys05vlu2rP9ERKmk0pIy/O9NPn8jQVAvI567+LtgjCNERRS7seiGHGC08aXQ0YV+EEwcoNgFxt1W3WAzsfZAtj9vW5ywYGzLJgGwHQqHgVdBj9IzukjaNia1Z/th9w+4faFQgNe1T4=
